# Generated by Django 4.2.7 on 2023-11-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_type', models.CharField(max_length=50)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pan_no', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('pin', models.CharField(max_length=6)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('loan_past', models.BooleanField(default=False)),
                ('credit_card', models.BooleanField(default=False)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
