# Generated by Django 4.2.7 on 2023-11-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_employee_type_form_employeetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='net_income',
            new_name='netincome',
        ),
    ]
