# Generated by Django 4.2.7 on 2023-11-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_net_income_form_netincome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='loan_past',
            new_name='past_loan',
        ),
    ]
