# Generated by Django 4.2.7 on 2023-11-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_form_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='purpose',
            new_name='purpose_of_loan',
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
