# Generated by Django 4.2.7 on 2023-11-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_purpose_form_purpose_of_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='employeeType',
            field=models.CharField(max_length=100),
        ),
    ]
