# Generated by Django 4.2.7 on 2023-11-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_form_credit_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('lenderID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=10)),
                ('lender_phone_no', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('min_creditscore', models.IntegerField()),
            ],
        ),
    ]
